### ISSUE TITLE
Allow use of single-store mode

### ISSUE THREAD

**Issue by bdnugget** [ActiveCampaign/module-integration#19]
When a store runs in single-store mode, the module throws an undefined index exception, because it tries to use $request['store'] in Core/Controller/Adminhtml/System/Config/Connect.php and Disconnect.php. This key comes from 'store_switcher' which doesn't exist when running in single-store mode.

I have created a PR with a workaround for this problem:
https://github.com/ActiveCampaign/module-integration/pull/18

**Comment by jorgeeurekalabs** [comment]
Hi,

Thank you very much for your contribution, this has been added and fixed.

Thank you.
