### ISSUE TITLE
Subscribers do not sync to ActiveCampaign

### ISSUE THREAD

**Issue by pdvracso** [ActiveCampaign/module-integration#21]
When someone subscribes to the native Magento Newsletter Subscribers function its not synced to ActiveCampaign.
"Newsletter Subscribers" can be found here _"Marketing > Communications > Newsletter Subscribers""_

Syncing newsletter subscribers and the opt-in information about customers is one of the basics this integrations should do.

**Comment by jorgeeurekalabs** [comment]
Hi,
In the new version of the module the Magento newsletter integration is already supported.

Thank you for your report.
