### ISSUE TITLE
Logger missing in construct

### ISSUE THREAD

**Issue by JoostWan** [ActiveCampaign/module-integration#27]
When there is an error with order data send it should be logged but logger is missing in construct. 

https://github.com/ActiveCampaign/module-integration/blob/main/Order/Model/OrderData/OrderDataSend.php#L430

**Comment by jorgeeurekalabs** [comment]
Hi,

Now it is logging correctly. The log is not included in this file because it is stored in the sendRequest that calls it $this->curl->orderDataSend.
