### ISSUE TITLE
API Delete error

### ISSUE THREAD

**Issue by JoostWan** [ActiveCampaign/module-integration#28]
When a customer creates a cart/quote the `AcOrderSyncId` is 0. This is updated when the cron with AbandonedCartSendData is triggered. But when the customer place the order before the trigger the value is still 0. 

Then this function will triggered when a order is placed, and there will be a `DELETE` API call with Order ID 0. That gives a error: 

```[2022-05-18 12:21:22] ActiveCampaign.CRITICAL: GuzzleHttp\Exception\ClientException: Client error: `DELETE https://XXXXX.api-us1.com/api/3/ecomOrders/0` resulted in a `404 Not Found` response:
{"message":"No Result found for EcomOrder with id 0"}```

**Comment by jorgeeurekalabs** [comment]
This issue has been fixed.
In addition, the field "Minimum inactivity time" has been added to set the minimum inactivity time.
