### ISSUE TITLE
Order sync not working when quote is deleted 

### ISSUE THREAD

**Issue by JoostWan** [ActiveCampaign/module-integration#29]
The Full order sync is not working because it want to get the original quote. But in our case the quote table is cleaned so for a old order the quote is removed from the quote table. This gives a error for the cronjob `ac_order_sync_cron_job`

https://github.com/ActiveCampaign/module-integration/blob/main/Order/Cron/OrderSyncCron.php#L90

**Comment by JelleGe** [comment]
Same issue here..

**Comment by jorgeeurekalabs** [comment]
This issue has been fixed.
