### ISSUE TITLE
OrderDataSend.php Errors: Cannot instantiate abstract class Magento\Framework\Model\ResourceModel\AbstractResource

### ISSUE THREAD

**Issue by bret-BSA** [ActiveCampaign/module-integration#31]
Magento 2.4.4
PHP 8.1

app\code\ActiveCampaign\Order\Model\OrderData\OrderDataSend.php

This is a careless mistake:

public function __construct(
        Context $context,
        \Magento\Framework\Registry $registry,
        AbstractResource $resource = null,
        AbstractDb $resourceCollection = null,
        ProductRepositoryInterfaceFactory $productRepositoryFactory,
        ImageFactory $imageHelperFactory,
        ActiveCampaignOrderHelper $activeCampaignOrderHelper,
        ActiveCampaignHelper $activeCampaignHelper,
        ConfigInterface $configInterface,
        Curl $curl,
        CustomerRepositoryInterface $customerRepositoryInterface,
        StoreRepositoryInterface $storeRepository,
        CustomerFactory $customerFactory,
        StoreManagerInterface $storeManager,
        CustomerModel $customerModel,
        AddressRepositoryInterface $addressRepository,
        Attribute $eavAttribute,
        CoreHelper $coreHelper,
        CustomerResource $customerResource,
        array $data = []
    )

SHOULD BE:

public function __construct(
        Context $context,
        \Magento\Framework\Registry $registry,
        ProductRepositoryInterfaceFactory $productRepositoryFactory,
        ImageFactory $imageHelperFactory,
        ActiveCampaignOrderHelper $activeCampaignOrderHelper,
        ActiveCampaignHelper $activeCampaignHelper,
        ConfigInterface $configInterface,
        Curl $curl,
        CustomerRepositoryInterface $customerRepositoryInterface,
        StoreRepositoryInterface $storeRepository,
        CustomerFactory $customerFactory,
        StoreManagerInterface $storeManager,
        CustomerModel $customerModel,
        AddressRepositoryInterface $addressRepository,
        Attribute $eavAttribute,
        CoreHelper $coreHelper,
        CustomerResource $customerResource,
        AbstractResource $resource = null,
        AbstractDb $resourceCollection = null,
        array $data = []
    )

**Comment by MTheProgrammer** [comment]
If you use PHPStorm, you will be notified with a warning: _Optional parameter is provided before the required one_. Besides, the class constructor has too many parameters.

**Comment by jorgeeurekalabs** [comment]
This issue has been fixed.
The latest version of the module is now compatible with PHP 8.1 and 8.2
