### ISSUE TITLE
Incorrect Json Serializer alias in ActiveCampaign\Core\Helper\Curl

### ISSUE THREAD

**Issue by MTheProgrammer** [ActiveCampaign/module-integration#40]
Class imports Helper Data as JsonHelper
use Magento\Framework\Json\Helper\Data as JsonHelper;

while declared type in the field is 
Magento\Framework\Serialize\Serializer\Json

which leads to incorrect method name usage.

```
[2022-10-05 08:59:16] main.CRITICAL: Error: Call to undefined method Magento\Framework\Json\Helper\Data::serialize() in /path/app/code/ActiveCampaign/Core/Helper/Curl.php:219
Stack trace:
#0 /path/app/code/ActiveCampaign/Customer/Observer/CustomerSaveAfter.php(74): ActiveCampaign\Core\Helper\Curl->createContacts()
#1 /path/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): ActiveCampaign\Customer\Observer\CustomerSaveAfter->execute()

```

BTW, maybe you should add PHPStan executed in GithubActions?

**Comment by MTheProgrammer** [comment]
I've created MR: https://github.com/ActiveCampaign/module-integration/pull/41
However, this optional Curl instantiated with new feels like code smell. I suggest that it should be configured with di.xml.

**Comment by d1m5n** [comment]
@wagator Is this issue going to be reviewed? Customers are unable to create an account with this error.

**Comment by bret-BSA** [comment]
Magento 2.4.5
PHP 8.1.1

vendor\activecampaign\active-campaign-core\Helper\Curl.php
line #348 $synclog->setRequest($this->jsonHelper->serialize($request));

this class is deprecated and does not contain the serialize method:
vendor\magento\framework\Json\Helper\Data.php

the correct class is:
vendor\magento\framework\Serialize\Serializer\Json.php

**Comment by MTheProgrammer** [comment]
I'll create a fork of that module if nobody is going to fix that.

**Comment by jorgeeurekalabs** [comment]
Thank you very much for your MR, this has already been fixed.
