### ISSUE TITLE
Code duplicated

### ISSUE THREAD

**Issue by pstuifzand** [ActiveCampaign/module-integration#48]
It seems a lot a code was duplicated in PR #39 . I don't think this is right.

These directories are duplicated with small changes.

- `Core/Core`
- `Customer/Customer`
- `Order/Order`
- `AbandonedCart/AbandonedCart`
- `SyncLog/SyncLog`

There are small differences that are not applied to the actual code.

**Comment by sergiuec** [comment]
> It seems a lot a code was duplicated in PR #39 . I don't think this is right.
> 
> These directories are duplicated with small changes.
> 
>     * `Core/Core`
> 
>     * `Customer/Customer`
> 
>     * `Order/Order`
> 
>     * `AbandonedCart/AbandonedCart`
> 
>     * `SyncLog/SyncLog`
> 
> 
> There are small differences that are not applied to the actual code.

In case for someone may be useful: On main branch the issue has been fixed, I don't understand why the fix has not been released yet but for now you could install the module from main branch by running the command:
`composer require activecampaign/module-integration:dev-main`
