### ISSUE TITLE
Reordering abandonded cart grid in any column causes SQLSTATE[23000]: Integrity constraint violation

### ISSUE THREAD

**Issue by aziwaan** [ActiveCampaign/module-integration#5]
Magento 2.3.5
PHP 7.3

To reproduce re-order any column in the abandoned carts data grid.  

Expected result:
Grid data is reloaded ascending/descending

Actual Result:
Grid becomes stuck and does not load reordered content

<img width="1472" alt="Screen Shot 2021-10-07 at 3 59 48 pm" src="https://user-images.githubusercontent.com/8869016/136323005-3ec94535-eb72-4064-82f6-e5c7910c7ea7.png">
<img width="2017" alt="Screen Shot 2021-10-07 at 3 57 21 pm" src="https://user-images.githubusercontent.com/8869016/136323012-cab6df22-2e6a-44f0-8e29-7ca526866663.png">

@activecampaign-sre 
@jordan-price

**Comment by jorgeeurekalabs** [comment]
Hi,

The sorting in the abandoned cart section now works correctly.

Thank you.
