### ISSUE TITLE
PLugin on GuestPaymentInformationManagementPlugin does not return $result which breaks Amazon Pay

### ISSUE THREAD

**Issue by MTheProgrammer** [ActiveCampaign/module-integration#55]
As in the title, this plugin after must return result. Otherwise it breaks webapi and instead of 'true' the response is '[]'.

AbandonedCart/Plugin/Checkout/Model/GuestPaymentInformationManagementPlugin.php

**Comment by jorgeeurekalabs** [comment]
This issue has been fixed.

Thank you
