### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by bret-BSA** [ActiveCampaign/module-integration#60]
Root composer.json requires activecampaign/module-integration 2.0.9, it is satisfiable by activecampaign/module-integration[2.0.9] from composer repo (https://repo.magento.com) but activecampaign/module-integration[dev-github/
v2.0.1, dev-github/v2.0.3, dev-main, dev-v2.0.4_correction, dev-rc_v2.0.4, v1.0.0, v2.0.0, ..., 2.0.8] from vcs repo (github https://github.com/ActiveCampaign/module-integration) has higher repository priority. The packages from the
 higher priority repository do not match your constraint and are therefore not installable. That repository is canonical so the lower priority repo's packages are not installable. See https://getcomposer.org/repoprio for details and assistance.

**Comment by jorgeeurekalabs** [comment]
This issue has been fixed.

Thank you
