### ISSUE TITLE
Abandoned Cart Admin Grid Shows Zero Item Carts

### ISSUE THREAD

**Issue by bret-BSA** [ActiveCampaign/module-integration#61]
The way I fixed this problem was updating the sql query in this file:

vendor/activecampaign/abandonedcart/Ui/Component/Listing/AbandonedCartDataProvider.php

from

->where("main_table.is_active = 1 AND quote_address.address_type = 'billing'");

to

->where("main_table.is_active = 1 AND quote_address.address_type = 'billing' AND main_table.items_count>0");

**Comment by jorgeeurekalabs** [comment]
This issue has been fixed.

Thank you
