### ISSUE TITLE
Remove version from composer.json or make it equal to the release version

### ISSUE THREAD

**Issue by ainigma32** [ActiveCampaign/module-integration#73]
Hi all,

In the latest release (2.0.18) the composer.json file contains a version node that says 2.0.17
https://github.com/ActiveCampaign/module-integration/blob/44ec9f174e92b59ef1494c440c6818f158f8b66f/composer.json#L5
That means that installations that use composer to install this module, will not be able to install this release from github (packagist).

Please make sure that the version in composer.json is equal to the tag used to create the release or, preferrably, remove the version from composer.json entirely.
For some background see [here](https://www.yireo.com/blog/2020-03-02-remove-version-from-composer-json-files-in-magento-modules)

Thanks in advance

**Comment by lundsted** [comment]
How has this not been fixed yet??

**Comment by duikb00t** [comment]
Please change this.

**Comment by jorgeeurekalabs** [comment]
This issue has been fixed.

Thank you
