### ISSUE TITLE
Warning: Undefined variable $customerEmail

### ISSUE THREAD

**Issue by indykoning** [ActiveCampaign/module-integration#78]
After updating the module and releasing it out monitoring software is reporting a lot of errors for:
> Warning: Undefined variable $customerEmail
in
https://github.com/ActiveCampaign/module-integration/blob/6cae92d9c6b23632e5bed7d08d5f5f89c4746fd3/Order/Model/OrderData/OrderDataSend.php#L294

which can be correct as it is only set if it is not an existing customer
https://github.com/ActiveCampaign/module-integration/blob/6cae92d9c6b23632e5bed7d08d5f5f89c4746fd3/Order/Model/OrderData/OrderDataSend.php#L213

**Comment by jorgeeurekalabs** [comment]
This issue has been fixed.

Thank you.
