### ISSUE TITLE
Composer version wrong in latest release

### ISSUE THREAD

**Issue by LucasVollebergh** [ActiveCampaign/module-integration#79]
Same issue as https://github.com/ActiveCampaign/module-integration/issues/73
I can't update trough composer because you forgot to change composer version. 

Not ideal, for other users experiencing this issue, you can install manually trough app/code

**Comment by jorgeeurekalabs** [comment]
Hi,

This has been fixed, however we always recommend installing/updating the module from the [Magento marketplace](https://commercemarketplace.adobe.com/activecampaign-module-integration.html).

Thank you.
