### ISSUE TITLE
Abandoned Cart Sync Not Completing

### ISSUE THREAD

**Issue by bret-BSA** [ActiveCampaign/module-integration#8]
Magento 2.4 ECE
PHP 7.4

activecampaign/module-integration/AbandonedCart/Model/AbandonedCartSendData.php

If a user adds an item to the cart and doesn't sign in and then abandons the cart, the customer_id and customer_email are NULL.  This causes the script to terminate with error message of true instead of continuing to the next element in the quotes collection.

                 $customerEmail = $quote->getBillingAddress()->getEmail();
                 if (!$customerEmail) {
                     $result['error'] = true;
                     return $result;
                 }
                 $websiteId  = $this->storeManager->getWebsite()->getWebsiteId();
                 $customerModel = $this->customerModel;

SHOULD BE:

                 $customerEmail = $quote->getBillingAddress()->getEmail();
                 if (!$customerEmail) {
                     continue;
                 }
                 $websiteId  = $this->storeManager->getWebsite()->getWebsiteId();
                 $customerModel = $this->customerModel;

**Comment by marceldekoning** [comment]
@bret-BSA,

This is not completely true because this would prevent a manual sync from throwing and error when an email address is not present. I made a patch that fixes the issue where an extra filter is applied when there's no $quoteId provided, and only throws an error when a quote id is provided:
```
Index: vendor/activecampaign/module-integration/AbandonedCart/Model/AbandonedCartSendData.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/activecampaign/module-integration/AbandonedCart/Model/AbandonedCartSendData.php b/vendor/activecampaign/module-integration/AbandonedCart/Model/AbandonedCartSendData.php
--- a/vendor/activecampaign/module-integration/AbandonedCart/Model/AbandonedCartSendData.php	(date 1643807718053)
+++ b/vendor/activecampaign/module-integration/AbandonedCart/Model/AbandonedCartSendData.php	(date 1643807718053)
@@ -189,6 +189,13 @@
                 'main_table.is_active',
                 '1'
             );
+
+        if (!$quoteId) {
+            $abandonedCarts->addFieldToFilter('customer_email', [
+                ['neq' => null]
+            ]);
+        }
+
         if ($quoteId) {
             $abandonedCarts->addFieldToFilter(
                 'main_table.entity_id',
@@ -214,8 +221,12 @@
             } else {
                 $customerEmail = $quote->getBillingAddress()->getEmail();
                 if (!$customerEmail) {
-                    $result['error'] = __('Customer Email does not exist.');
-                    return $result;
+                    if ($quoteId) {
+                        $result['error'] = __('Customer Email does not exist.');
+                        return $result;
+                    }
+
+                    continue;
                 }
                 $websiteId  = $this->storeManager->getWebsite()->getWebsiteId();
                 $customerModel = $this->customerModel;

```

**Comment by bret-BSA** [comment]
Again, an abandoned cart can have a value of NULL for customer_id and your script will return the error without processing the rest of the abandoned carts. What really should be done is to filter the sql query on customer_id:

$abandonedCarts = $this->quoteResourceCollectionFactory->create()
            ->addFieldToSelect('*')
            ->addFieldToFilter('main_table.' . self::AC_SYNC_STATUS, [
                ['neq' => CronConfig::SYNCED]
            ])
            ->addFieldToFilter(
                'main_table.customer_id',
                ['neq' => 'NULL']
            )
            ->addFieldToFilter(
                'main_table.is_active',
                '1'
            );

**Comment by bret-BSA** [comment]
I would like to further clarify my response. If a quote has NULL values for customer_id and customer_email, your script will return an error and the script will never get pass this quote. Magento does not delete old quotes.

**Comment by jorgeeurekalabs** [comment]
Hi,
This has been fixed, the abandoned carts sync correctly.

Thank you.
