### ISSUE TITLE
Abandoned Cart Sync - Items From Previous Cart Recorded On Next Cart

### ISSUE THREAD

**Issue by bret-BSA** [ActiveCampaign/module-integration#9]
Magento 2.4 ECE
PHP 7.4

activecampaign/module-integration/AbandonedCart/Model/AbandonedCartSendData.php

The $quoteItemsData array needs to be re-initialized for each abandoned cart.

        $abandonedCarts->setPageSize($numberOfAbandonedCart);
        foreach ($abandonedCarts as $abandonedCart) {
            $connectionId = $this->coreHelper->getConnectionId($abandonedCart->getStoreId());
            $customerId = $abandonedCart->getCustomerId();

SHOULD BE:

        $abandonedCarts->setPageSize($numberOfAbandonedCart);
        foreach ($abandonedCarts as $abandonedCart) {
            $quoteItemsData = array();
            $connectionId = $this->coreHelper->getConnectionId($abandonedCart->getStoreId());
            $customerId = $abandonedCart->getCustomerId();

**Comment by jorgeeurekalabs** [comment]
Hi,

This issue has been fixed.

Thank you.
